186957029 finish undo redo tables
concord-consortium/codap pull request #1149
Opened 2024-03-06 06:22 UTC by nstclair-cc

@kswenson - I added undo/redo tests in this PR:

- verify edit attribute properties with undo and redo
- verify rename attribute with undo and redo
- verify hide and showAll attribute with undo and redo
- verify delete attribute with undo and redo
- verify index menu insert case and delete case work (NOTE: for this one Jtests were throwing me fix radix errors, but I wasn't sure if it was worth the time to investigate at this stage. If it's an easy fix though, could you please take a look starting around lines 192 where I commented out code? I think it has to do with parseInt() but I'm not sure)
- For remaining index menu tests, we have a PT bug to fix before adding checks (#187127871)
- For table component, I added the check "closes and reopens existing case tables with undo and redo." Also note PT #187033159 for adding a check to undo/redo of a table Collection name

Thanks very much! :)

2024-03-08 01:09 UTC, kswenson requested changes
👍 Generally looks good -- a couple of suggested tweaks to the test code and some formatting consistency to address.

2024-03-08 01:09 UTC, kswenson commented on v3/cypress/e2e/table.spec.ts
> +     table.getColumnHeaders().should("have.length", numOfAttributes - 1)
Indenting looks off here as well.

2024-03-08 01:09 UTC, kswenson commented on v3/cypress/e2e/table.spec.ts
> +       table.getAttribute(name).rightclick({ force: true })
This was here before but I'm not sure why. It isn't testing any table functionality and shouldn't be necessary.

2024-03-08 22:43 UTC, nstclair-cc commented on v3/cypress/e2e/table.spec.ts
> +       table.getAttribute(name).rightclick({ force: true })
Yeah, I don't know, either. ¯\_(ツ)_/¯ 

I decided to remove the lines of code in any event since I don't think we need it.

2024-03-08 22:44 UTC, nstclair-cc commented on v3/cypress/e2e/table.spec.ts
> +       table.getAttribute("Height").should("not.have.text", newName)
I updated the commenting to reflect this.

2024-03-08 22:59 UTC, nstclair-cc commented
Kirk -- thanks very much! I think I was able to address the indenting issues in Visual Studio Code, but please do let me know if you see anything. I also followed up on the remaining comments.

I saw this in the earlier commit, but do you understand why one of the `codecod/project` checks is failing? If it's something I can fix, I'm all ears.

2024-03-11 21:36 UTC, kswenson approved these changes
👍 Changes look good

2024-03-11 21:37 UTC, merged