186227299 automation inspector table
concord-consortium/codap pull request #1257
Opened 2024-05-13 22:52 UTC by nstclair-cc

[PT 186227299](https://www.pivotaltracker.com/story/show/186227299) Automation for Inspector menu options of case table

This PR is an initial pass on Automation for Inspector menu options in the case table. The tests include:

- should open dataset information button and make changes 
- select a case and delete the case from inspector menu 
- select a case and delete unselected cases from inspector menu 
- check delete all cases from inspector menu
- check hide/show attribute from inspector menu
- check New Attribute from inspector menu with undo/redo

I also added `cy.log()` in `table.spec.ts` for the tests that include undo/redo since that wasn't there initially in the code.

Note the missing undo/redo checks due to [PT 187597588](https://www.pivotaltracker.com/story/show/187597588).

Also I noticed it looks like we haven't worked on Set Aside Cases yet? I added a PT story here for that: [PT 187597833](https://www.pivotaltracker.com/story/show/187597833)

Jest is complaining about the variables with lines like `'initialRowCount' is assigned a value but never used`. I don't know why Cypress is forcing that those variables are there, but if I take the variables out the tests stop working. ¯\_ (ツ)_/¯ Let me know if there are easy fixes here!

I've added two more data-ids to the code for opening the Information button. Please let me know if this causes any issues; otherwise, I'll assume everything is working fine.

2024-05-13 22:53 UTC, nstclair-cc commented on v3/cypress/e2e/table.spec.ts
> +     let initialRowCount, postInsertRowCount, postDeleteRowCount
Jest is complaining about the variables with lines like 'initialRowCount' is assigned a value but never used. I don't know why Cypress is forcing that those variables are there, but if I take the variables out the tests stop working. ¯_ (ツ)_/¯ Let me know if there are easy fixes here!

2024-05-23 19:45 UTC, johnTcrawford requested changes
Mostly good. But please:
1. Put the page-specific IDs where they belong;
2. Fix the identical cy.log("...") messages;
3. Fix the formatting, that is the incorrect number of spaces/tabs;
4. Optional: remove the unnecessary radix arg.
I'm very sorry to have started this review last week, but never finished until now.

2024-05-23 19:45 UTC, johnTcrawford commented on v3/cypress/e2e/table.spec.ts
> +      cy.log("check for undo/redo after delete")
It is not helpful to have have 14 different cy.log statements, with identical messages of "check for undo/redo after delete". I'm counting the 3 above that are commented out (for now), and the 10 below. Please give them distinct messages, perhaps saying *what* was deleted, followed by undo/redo.

2024-05-24 22:19 UTC, kswenson commented on v3/cypress/support/elements/table-tile.ts
> +     if (name !== "") {
They are different: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness. Strict equality comparisons are generally preferred over their looser cousins.

2024-05-31 19:00 UTC, kswenson approved these changes
👍 LGTM

2024-05-31 19:00 UTC, merged