182089941 log string fixes
concord-consortium/codap pull request #1454
Opened 2024-09-04 20:28 UTC by eireland

2024-09-04 22:03 UTC, kswenson requested changes
👍 Generally looks good -- a handful of minor suggestions.

2024-09-04 22:03 UTC, kswenson commented on v3/src/components/graph/components/parent-toggles.tsx
> +        log: isOnlyLastShown ? "Disable last parent toggle" : "Enable last parent toggle"
Should probably be something more like:
```suggestion
        log: isOnlyLastShown ? "Disable only showing last parent toggle" : "Enable only showing last parent toggle"
```

2024-09-04 22:03 UTC, kswenson commented on v3/src/components/tool-shelf/options-button.tsx
> +      log: logStringifiedObjectMessage("Show web view: %@", {url})
Could use `logMessageWithReplacement` to just render the url without the braces.

2024-09-04 22:03 UTC, kswenson commented on v3/src/components/web-view/web-view-inspector.tsx
> +      log: logStringifiedObjectMessage("Change web view URL: %@", {url})
Could use `logMessageWithReplacement` to just render the url without the braces.

2024-09-04 22:24 UTC, tealefristoe approved these changes
Looks good 👍

2024-09-04 22:24 UTC, tealefristoe commented on v3/src/components/case-table/case-table-tool-shelf-button.tsx
> +      log: "create New Empty DataSet"
Capitalize "Create"?

2024-09-05 16:58 UTC, eireland commented on v3/src/components/calculator/calculator-title-bar.tsx
> +        log: logStringifiedObjectMessage("Close calculator", { type: kCalculatorTileType })
Why add the calculator type to the log message string if we already state that we closed a calculator?

2024-09-05 22:00 UTC, kswenson commented on v3/src/components/calculator/calculator-title-bar.tsx
> +        log: logStringifiedObjectMessage("Close calculator", { type: kCalculatorTileType })
Fair enough.

2024-09-05 22:02 UTC, kswenson approved these changes
👍 LGTM

2024-09-06 17:53 UTC, merged