Adds language menu UI to CFM bar
concord-consortium/codap pull request #1493
Opened 2024-09-17 00:33 UTC by eireland

This adds the UI for language menu to the CFM bar. The UI is currently non-functional.

2024-09-18 13:12 UTC, tealefristoe approved these changes
Looks good 👍 

Would `window.location.replace()` redirect to the new url properly? https://developer.mozilla.org/en-US/docs/Web/API/Location/replace

Also, it would be good to increase code coverage before merging. It should be possible to test `makeNewLocaleUrl` in a jest test to make sure it correctly constructs a new url, even if you can't test the actual redirection.

2024-09-18 13:12 UTC, tealefristoe commented on v3/src/lib/use-cloud-file-manager.ts
> +  let baseURL = "https://codap3.concord.org/branch/main/"
I assume this `baseURL` basically never comes up, but do we want it to be a branch link? Should it just be `https://codap3.concord.org`?

2024-09-18 17:14 UTC, kswenson requested changes
👍 Menu code looks fine. Don't worry about the url-switching code -- none of that should be necessary in v3. See comment elsewhere for details. I would just remove it and make this PR UI-only.

2024-09-18 17:14 UTC, kswenson commented on v3/cypress/e2e/cfm.spec.ts
> +  it("verify langugae menu is present", () => {
```suggestion
  it("verify language menu is present", () => {
```

2024-09-18 17:14 UTC, kswenson commented on v3/src/lib/use-cloud-file-manager.ts
> +            window.location.href = makeNewLocaleUrl(langCode, window.location.href)
The need to reload the page when switching languages in v2 was an artifact of SproutCore's approach to localization. In v3 we're just going to change some state and force everything to re-render. You can just remove the `makeNewLocaleUrl` function and make this PR UI only for now.

2024-09-19 05:07 UTC, kswenson approved these changes
👍 Looks good -- one other thing I just noticed which you might want to address is that in v2 the current language isn't listed in the menu, whereas in this PR it is listed. I could see an argument for listing it, but if it is listed it should probably have a checkmark indicating that it's already the currently selected option, so removing it might be simpler. This has the advantage of not tempting users to "switch" to the current language.

2024-09-19 22:21 UTC, merged