188497532 graph map filter formula editor
concord-consortium/codap pull request #1609
Opened 2024-11-09 04:12 UTC by eireland

Changes the graph filter formula editor to use the more complete formula editor modal.

Adds Edit Filter Formula to the map inspector panel, which also uses the more complete formula editor modal. Note that the actual filtering has not been implemented in the graph.

2024-11-12 19:01 UTC, tealefristoe approved these changes
Looks good 👍 

Only big thing to do is remove the outdated `edit-filter-formula-modal.tsx`.

One other thing you might consider doing is making `dataConfig.filterFormula.addOrEditFormalString` a view on the model so you don't repeat the same code in both `hide-show-menu-list.tsx` files.

2024-11-12 19:02 UTC, tealefristoe requested changes
Actually it looks like a cypress test is failing after this change. You should apply the `run regression` label to PRs to make sure all tests pass before requesting a review.

2024-11-12 20:53 UTC, kswenson commented
> One other thing you might consider doing is making `dataConfig.filterFormula.addOrEditFormalString` a view on the model so you don't repeat the same code in both `hide-show-menu-list.tsx` files.

Localizable strings for menu items isn't really a model-level concern, but sharing the code some other way, e.g. a custom hook that might allow some other part of the implementation to be shared might make sense.

2024-11-12 22:22 UTC, eireland commented on v3/src/components/graph/components/inspector-panel/hide-show-menu-list.tsx
> -import { EditFilterFormulaModal } from "../../../common/edit-filter-formula-modal"
EditFilterFormulaModal is still being used in the case table/card, and will be removed when this [story](https://www.pivotaltracker.com/story/show/188497528) is worked on.

2024-11-12 22:35 UTC, kswenson approved these changes
👍 LGTM

2024-11-13 00:24 UTC, tealefristoe approved these changes
Looks good 👍 

Sorry for the misunderstanding with `EditFilterFormulaModal` earlier. I was confused because it's used in two files called `hide-show-menu-list.tsx`, and this PR modifies two files called `hide-show-menu-list.tsx`, but they weren't the same two... there are actually three files with that same name 😕

2024-11-13 17:00 UTC, merged