188527686 formula editor improvements
concord-consortium/codap pull request #1689
Opened 2024-12-16 22:09 UTC by eireland

Makes formula editor modal resizable.
Removes default codap modal header.

2024-12-18 17:48 UTC, bfinzer commented
I'm seeing two lint warnings: `ModalCloseButton` and `ModalHeader` are defined but not used in edit-formula-modal.tsx.

2024-12-18 17:55 UTC, bfinzer commented
In the V2 formula editor text wraps when it reaches the right edge. This should be the behavior in V3 as well. If this is easy to bring about, it could be part of this PR, otherwise a separate story.

2024-12-18 18:01 UTC, bfinzer approved these changes
👍🏻LGTM
Just a couple notes.

2024-12-18 20:53 UTC, kswenson requested changes
👍 Generally looks good -- see inline suggestions.

>In the V2 formula editor text wraps when it reaches the right edge. This should be the behavior in V3 as well. If this is easy to bring about, it could be part of this PR, otherwise a separate story.

According to ChatGPT, CodeMirror can be configured to wrap text by adding `EditorView.lineWrapping` to the list of extensions when initializing the editor.

2024-12-18 20:53 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.tsx
> +  const [dimension, setDimension] = useState({ width: minWidth, height: minHeight })
```suggestion
  const [dimensions, setDimensions] = useState({ width: minWidth, height: minHeight })
```

2024-12-18 20:53 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.tsx
> +    setDimension({ width: minWidth, height: minHeight })
Are we sure we want to reset the size on close? I can see an argument that retaining its size across invocation would be desirable.

2024-12-18 20:53 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.tsx
> +  const minHeight = 180
These values appear here and in the CSS. Either import the values from the .css or use CSS variables, e.g. `--default-codap-modal-width` and `--default-codap-modal-height`, which are accessible from CSS and JS.

2024-12-18 20:53 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.tsx
> +    const modalRect = document.querySelector(".codap-modal-content")?.getBoundingClientRect()
Document-wide queries are fragile -- what if there are two modals showing? Either use a ref or a library like `react-resize-detector`.

2024-12-18 20:53 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.tsx
> +      })
I recommend rounding these values to integer pixels -- they're much easier to deal with when debugging and I don't think fractional pixel widths are necessary for users.

2024-12-18 20:53 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.scss
> +  min-width: 400px;
These values appear here and in the JS. They should be shared. See comment elsewhere for more details.

2024-12-24 22:15 UTC, kswenson approved these changes
👍 Looks good -- just a few small suggestions.

2024-12-24 22:15 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.scss
> +    min-width: 400px;
Could this be:
```suggestion
    min-width: $edit-formula-modal-min-width-px;
```

2024-12-24 22:15 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.scss
> +          width: calc(100% - 50px);
Comment or named constant for the `50px` value

2024-12-24 22:15 UTC, kswenson commented on v3/src/components/common/edit-formula-modal.scss
> +    bottom: 0px;
```suggestion
    bottom: 0;
```
For consistency

2024-12-26 19:37 UTC, merged