Export game view
concord-consortium/codap pull request #1690
Opened 2024-12-17 15:52 UTC by scytacki

This makes `isPlugin` a serialized field in V3. That is necessary so we can keep track of which WebViews are v2 GameViews and which are v2 WebViews.
The `setIsPlugin` is marked as `withoutUndo` so when a plugin is added and it sets up the iframe phone this change of the document state doesn't add an action to the undo stack.

The `contextStorage` field is added to the DataSet conversion. This was necessary to get a document to load with a plugin that had created a data table. However this document is still broken because it data context collections seem to be reversed and disconnected.

Name handling in GameViews adds more complexity to the already complex name and title handling. GameViews store their name in componentStorage.currentGameName instead of componentStorage.gameName

2024-12-18 03:19 UTC, kswenson approved these changes
👍 Looks good -- I added a commit which fixed the game view `name` issue you pointed out.

2024-12-18 13:57 UTC, kswenson requested changes
Two thoughts occurred to me this morning:
1. Instead of a Boolean `isPlugin` property, it should be a `subType` property with value `plugin`. That way when `DG.GuideView` is implemented, it can be `subType` `guide`. I would leave it undefined for standard web views.
2. The importer for `DG.GameView` should set the `subType` property to `plugin`.

2024-12-20 18:51 UTC, kswenson commented
> Two thoughts occurred to me this morning:
> 
> 1. Instead of a Boolean `isPlugin` property, it should be a `subType` property with value `plugin`. That way when `DG.GuideView` is implemented, it can be `subType` `guide`. I would leave it undefined for standard web views.
> 2. The importer for `DG.GameView` should set the `subType` property to `plugin`.

After consultation with @scytacki, I added a commit which implemented `#1` above. Turns out `#2` was already implemented in what @scytacki had done.

2024-12-20 18:53 UTC, kswenson approved these changes
After consultation with @scytacki, I addressed my concerns in a follow-up commit.

2024-12-20 19:04 UTC, scytacki reviewed
I can't officially approve but it looks good to me. 

My only comment is about allowing the v3 WebView to be turned back into a v2 WebView via the subType setter.

2024-12-20 19:04 UTC, scytacki commented on v3/src/components/web-view/web-view-model.ts
> +    setSubType(subType: WebViewSubType) {
Maybe you want to allow `undefined` here so the subtype can be reverted back to the default non plugin, non guide.

2024-12-20 19:05 UTC, kswenson commented
> I can't officially approve but it looks good to me. 
> 
> 
> 
> My only comment is about allowing the v3 WebView to be turned back into a v2 WebView via the subType setter.

Good catch -- I meant to do that. I'll update before merging.

2024-12-20 21:43 UTC, merged