188651494 pixi js integration
concord-consortium/codap pull request #1697
Opened 2024-12-20 01:39 UTC by nstclair-cc

2025-01-06 19:33 UTC, scytacki requested changes
Getting closer. I left some comments of things to change so we can see if the cypress tests will run in GitHub Actions.

2025-01-06 19:33 UTC, scytacki commented on .github/workflows/graph-pixi-tests.yml
> +cypress:
This cypress section, a GitHub Actions "job", needs to be indented to the same spot as `re_run:`.
I found that by looking for the log of running this workflow: https://github.com/concord-consortium/codap/actions/runs/12474798288

Since the workflow isn't running yet it is hard to know if there are other things broken.

2025-01-06 19:33 UTC, scytacki commented on .github/workflows/graph-pixi-tests.yml
> +name: Regression Label
This should be renamed to something like "Graph Pixi Tests". 
That will make it easier to tell if it is working or not. It currently has the same name as another workflow.

Below are the results right now. This workflow is the one with the `on: push` below it. It doesn't have any running jobs because of the syntax error (see comment below).
<img width="578" alt="image" src="https://github.com/user-attachments/assets/dd826431-6ab3-4557-9880-2d9648eb0394" />

2025-01-08 00:10 UTC, kswenson approved these changes
👍 LGTM -- just a couple of suggestions. Beyond that, @scytacki should have the final word.

2025-01-08 16:23 UTC, scytacki requested changes
I think this is mostly done. 

I left a couple of inline comments of things to change.

The reason the Jest tests look like they are failing is because the changed files are triggering the CODAP v2 workflow. So it is trying to run the v2 jest tests.

That happens because of the filters setup for the various workflows. So to fix it you could update this section of v3.yml: https://github.com/concord-consortium/codap/blob/9b994cc5f7f1835cf7fae2ef5f0381c6ec008e5e/.github/workflows/v3.yml#L5-L7
To include `- '.github/workflows/graph-pixi-tests.yml'

And update this section:
https://github.com/concord-consortium/codap/blob/9b994cc5f7f1835cf7fae2ef5f0381c6ec008e5e/.github/workflows/ci.yml#L5-L12
to exclude the workflow.

At one point I thought Teale was just going to remove the v2 workflows from the v3 branch but it looks like that didn't happen.

2025-01-08 16:23 UTC, scytacki commented on .github/workflows/graph-pixi-tests.yml
> +  jest:
I don't think it is necessary to run the jest tests here. They should already be run by the main workflow.  But perhaps you added them just make sure they were working here since they are failing in the main workflow.

2025-01-08 16:23 UTC, scytacki commented on .github/workflows/graph-pixi-tests.yml
> +            cypress/e2e/pixi-interaction
I'd assume the cypress tests are inside of the v3 folder so it shouldn't be necessary to add that here. Just listing v3 should be enough.

2025-01-08 19:25 UTC, scytacki requested changes
Closer. :) I'm not sure if I missed them before, or you just added them but the `lint` and `build` jobs should not be needed in the `graph-pixi-tests.yml` workflow.

2025-01-08 19:25 UTC, scytacki commented on .github/workflows/graph-pixi-tests.yml
> +  lint:
I'm not sure if I missed this before or you added it recently, but I don't think `lint` should be run in this worlkflow. It is redundant with the lint that is run during main `v3.yml` workflow.

2025-01-08 19:25 UTC, scytacki commented on .github/workflows/graph-pixi-tests.yml
> +  build:
I'm also not sure if I missed this before, but this whole `build` job shouldn't be needed. The cypress job below runs the webpack dev server which will build the app.

2025-01-08 21:02 UTC, scytacki approved these changes
Looks good. 👍

2025-01-08 21:10 UTC, nstclair-cc commented
> Closer. :) I'm not sure if I missed them before, or you just added them but the `lint` and `build` jobs should not be needed in the `graph-pixi-tests.yml` workflow.

Oh, phew—you’re right! I left that in because I didn’t want to assume it wasn’t needed. Thanks for catching that! Let’s try again with the review, @scytacki.

2025-01-08 21:10 UTC, merged