183016745 empty case table
concord-consortium/codap pull request #451
Opened 2022-08-25 22:39 UTC by eireland

Shows an empty case table on load

2022-08-25 23:39 UTC, bfinzer requested changes

2022-08-25 23:39 UTC, bfinzer commented on v3/src/components/app.tsx
> +  function createNewTable() {
Suggest createNewStarterDataset since the table appears as a side effect

2022-08-25 23:39 UTC, bfinzer commented on v3/src/components/app.scss
> +    .add-new-table-button {
This style isn't used, right?

2022-08-25 23:42 UTC, bfinzer commented
To help us distinguish V3 pull requests from V2 pull requests, we start the name with "V3—" and we use the magenta V3 label

2022-08-26 00:06 UTC, kswenson approved these changes
👍 Nothing to add beyond Bill's comments

2022-08-26 00:06 UTC, kswenson commented on v3/src/components/case-table/use-rows.ts
> +            const formatted = (numValue != null) && isFinite(numValue) ? format(formatStr)(numValue) : strValue
FYI, the way the semicolon got in there was that semicolons can be required depending on how the next line begins. That used to be true here, but then the code for the subsequent line was changed without removing the semicolon.

2022-08-26 15:49 UTC, bfinzer approved these changes
👍🏻 LGTM

2022-08-26 18:14 UTC, merged