183016994 dataset switching popup
concord-consortium/codap pull request #454
Opened 2022-08-30 21:58 UTC by eireland

Adds ability to switch data sets via dropdown

2022-09-01 03:36 UTC, kswenson requested changes
👍 Looks good -- just a couple suggestions

2022-09-01 03:36 UTC, kswenson commented on v3/src/components/data-summary.tsx
> +    }
```suggestion
    return null
```
You don't need the `else` here.

2022-09-02 15:52 UTC, bfinzer approved these changes
👍🏻 LGTM

2022-09-02 18:26 UTC, kswenson approved these changes
👍 Changes look good

2022-09-03 00:30 UTC, merged