Adds version and build number to the hello codap area
concord-consortium/codap pull request #456
Opened 2022-08-31 19:36 UTC by eireland

2022-09-01 20:56 UTC, kswenson requested changes
👍 This captures the basic idea. Need to figure out what we actually want to do with the build number.

2022-09-01 20:56 UTC, kswenson commented on v3/package.json
> +  "version": "v3.0.0-build.700",
Version listed here should not have the "V" prefix. It's fine to display it that way to the user if desired, but this field is processed by npm and others. I gather the "700" was an attempt to push it beyond the current v2 build number? If that's a goal I'd probably start at "1000" just to make sure they don't overlap, but I'm not sure that actually matters. I was imagining we'd just start low and build.

2022-09-02 16:18 UTC, bfinzer approved these changes
👍🏻 LGTM
To what extent can we automate updating the version information? And when should it be automated? Perhaps the build number gets incremented every time there's a merge to main?

2022-09-02 18:23 UTC, kswenson commented
I talked to @bfinzer and he suggested starting the build numbers at `1000`.

2022-09-02 18:25 UTC, kswenson commented
> 👍🏻 LGTM To what extent can we automate updating the version information? And when should it be automated? Perhaps the build number gets incremented every time there's a merge to main?

Automating the build number incrementing will require some research and probably shouldn't hold up this PR.

2022-09-06 22:35 UTC, merged