181889611 rename attribute
concord-consortium/codap pull request #484
Opened 2022-09-29 20:03 UTC by eireland

Adds ability to rename attribute in the case table column header. Column header changes into an input component to allow change

2022-09-29 22:30 UTC, bfinzer commented
I notice that soon after the name gets focus for editing the tooltip comes up. I think you were trying to fix that, right?

2022-09-29 22:42 UTC, bfinzer requested changes
One question needs answering.

2022-09-29 22:42 UTC, bfinzer commented on v3/src/components/case-table/column-header.tsx
> +    const trimTitle = editingAttrName?.trim()
I like to declare these in the clause where they are used

2022-09-29 22:42 UTC, bfinzer commented on v3/src/data-model/data-set.ts
> +          attrNameMap[name] = attributeID
Where does the entry in the attrNameMap for the old name get deleted?

2022-09-29 23:34 UTC, kswenson requested changes
👍 I was going to suggest a couple of tweaks but then after trying them locally went ahead and added a commit (after showing them to @eireland). I also made a suggestion about clearing out the old attribute name from the dataset (also pointed out by Bill). Finally, as we discussed when we met, I think you should try to remove the inner input highlight so that there isn't a double-highlight when editing and it follows the convention for editing body cells.

2022-09-30 01:05 UTC, kswenson approved these changes
👍 Changes look good

2022-09-30 15:08 UTC, merged