Table styling
concord-consortium/codap pull request #517
Opened 2022-10-15 00:16 UTC by eireland

Adds more thematic styling for menu and modals.

2022-10-18 22:35 UTC, kswenson requested changes
👍 Generally looks good -- I like the use of Chakra theming. Just a couple of comments, the main one being to remove the undesirable change to column header formatting.

2022-10-18 22:35 UTC, kswenson commented on v3/src/components/case-table/insert-cases-modal.tsx
> +      <FormLabel h="20px" display="flex" flexDirection="row" alignItems={"center"}># cases to insert:
```suggestion
      <FormLabel h="20px" display="flex" flexDirection="row" alignItems="center"># cases to insert:
```
Consistency

2022-10-18 22:35 UTC, kswenson commented on v3/src/components/case-table/case-table.scss
> +      .rdg-header-row {
```suggestion
    .rdg-header-row {
```
`.rdg-header-row` is not inside `.rdg-row`, so this change simply disables column header formatting.

2022-10-20 15:19 UTC, kswenson approved these changes
👍 Changes look good

2022-10-20 16:40 UTC, bfinzer approved these changes
👍🏻LGTM

2022-10-20 22:30 UTC, merged