181465538 inspector panel
concord-consortium/codap pull request #559
Opened 2022-11-17 17:08 UTC by eireland

Adds a generic inspector panel that will show specific tools depending on the component.
Temporarily:
1. Graph inspector panel is always showing on top of the graph.
2. Table inspector is shown and hidden by clicking anywhere in the case table.
3. None of the buttons do anything at the moment.

Note: Camera icon is not the same as V2.

2022-11-17 21:43 UTC, bfinzer commented
I took a brief look at the V2 architecture and verified that as I mentioned the Inspector knows virtually nothing about what a target component will want. It asks the target for its icons and the hooks that will be triggered by each. I like this because, for one thing, it generalizes nicely to plugins.
Just something to keep in mind.

2022-11-17 21:45 UTC, bfinzer approved these changes
👍🏻LGTM
I think we'll revisit the architecture question I raise once we start getting serious about each component's inspector.

2022-11-23 03:08 UTC, kswenson requested changes
👍 Almost there -- one more minor refactor to eliminate some redundancy.

2022-11-23 03:08 UTC, kswenson commented on v3/src/components/graph/components/graph-inspector.tsx
> +}
You could make the `InspectorButton` reusable as well with something like the following, which gives more control to the client:
```
interface IInspectorButtonProps {
  children: ReactNode
  moreOptions: boolean
}
const InspectorButton = ({ children, moreOptions }: IInspectorButtonProps) => {
  return (
    <Button className="inspector-tool-button">
      {children}
      {moreOptions && <MoreOptionsIcon className="more-options-icon"/>}
    </Button>
  )
}

2022-11-23 03:10 UTC, kswenson approved these changes
👍 Never mind my previous review -- I see you've already moved in that direction in a subsequent PR so let's merge this as is.

2022-11-23 03:24 UTC, merged