V3: Adds theme styling for checkboxes
concord-consortium/codap pull request #573
Opened 2022-12-02 16:35 UTC by eireland

Adds palette for ruler inspector

2022-12-02 18:07 UTC, kswenson requested changes
👍 Generally looks good -- I made some suggestions for simplifying the code.

2022-12-07 18:59 UTC, eireland commented on v3/src/components/graph/components/inspector-panel/graph-measure-panel.tsx
> +                      : 0
Yes. We'll have to work on this again when we have movable components

2022-12-07 19:17 UTC, kswenson approved these changes
👍 Looks good -- just one suggestion about consistency between file names and component names that should be addressed.

2022-12-07 19:17 UTC, kswenson commented on v3/src/components/graph/components/inspector-panel/graph-measure-panel.tsx
> +export const GraphMeasurePalette = ({graphModel}: IProps) => {
I just noticed that the component is `GraphMeasurePalette` while the files are `graph-measure-panel.*`. Seems like they should be consistent.

2022-12-07 19:17 UTC, kswenson commented on v3/src/components/graph/components/inspector-panel/graph-measure-panel.tsx
> +      buttonLocation={graphModel.plotType === "casePlot" || graphModel.plotType === "dotChart" ? 25 : 75}
What's needed is a way to encapsulate all of the plot-specific information in one place, but that can wait for another day.

2022-12-07 19:21 UTC, merged