V3—brush palette changes tied to graph model
concord-consortium/codap pull request #583
Opened 2022-12-07 22:24 UTC by bfinzer

* Took this opportunity to introduce UseGraphModel rather than drill the graphModel down further
* point-format-palette now passes all user-initiated changes to the graphModel
* useGraphModel and background observe graphModel changes and redisplay as needed

2022-12-08 23:17 UTC, kswenson requested changes
👍 Looks good -- I made a couple of specific suggestions and then a couple broader ones about what I'm calling dependency curation. It seems like a pattern is developing of dereferencing all of the leaf values that a component needs at the top of the component and then using them throughout the component in way that result in long dependency lists on `useCallback`s and `useEffect`s. This makes it harder to reason about when functions are being invalidated and when effects are run, as well as harder to tell whether there might be any unnecessary dependencies listed (since those aren't highlighted by the linter). The broader recommendation, which doesn't necessarily need to happen as part of this PR, is to give some consideration to moving some of those dereferences inside the corresponding callback or effect in cases where invalidation of the function or running the effect function isn't necessary. We can discuss as part of a sync review if that would be useful.

2022-12-08 23:17 UTC, kswenson commented on v3/src/components/graph/models/graph-model.ts
> +  args: [GraphAttrRole, string]
```suggestion
  args: [string | number | boolean]
```
All of the actions in question take a single argument of one of these types.

2022-12-09 16:22 UTC, bfinzer commented on v3/src/components/graph/models/graph-model.ts
> +    pointStrokeSameAsFill: types.optional(types.boolean, false),
It's a separate property because it reflects a user decision rather than a computation.

2022-12-09 17:02 UTC, bfinzer commented on v3/src/components/graph/components/inspector-panel/point-format-panel.tsx
> +    forceUpdate()
Nice. Learned something!

2022-12-09 17:07 UTC, merged