Build 3.0.0-1085
concord-consortium/codap pull request #603
Opened 2022-12-24 04:48 UTC by tejal-shah

2022-12-27 17:44 UTC, kswenson requested changes
👍 Generally looks good, but I think we should use a version number that makes it clear that this is not an official release -- something like `3.0.0-pre.1085` or `3.0.0-alpha.1085` as suggested below.

2022-12-27 17:44 UTC, kswenson commented on v3/package.json
> +  "version": "3.0.0-1085",
I think we should use a version number that makes it clear that this is not an official release -- something like `3.0.0-pre.1085` or `3.0.0-alpha.1085`.

2023-01-04 00:27 UTC, tejal-shah commented
@kswenson , I've updated the version number to 3.0.0-pre.1085

2023-01-04 17:27 UTC, kswenson approved these changes
👍 LGTM

2023-01-04 17:32 UTC, merged