Adds ui for legend point color setting in inspector palette
concord-consortium/codap pull request #607
Opened 2022-12-28 20:28 UTC by eireland

2022-12-28 22:59 UTC, bfinzer approved these changes
👍🏻LGTM

2022-12-29 23:09 UTC, kswenson requested changes
👍 Code looks fine -- my main suggestion is to add some comments to some parts that weren't immediately obvious to me, e.g.
- `-webkit`-only CSS
- add `TODO` comments where the code will have to change once the necessary model support for legend colors is in place. I was briefly confused as to how calling `setPointColor()` could possibly change a legend category color before realizing that it's not supposed to (yet).

2023-01-10 05:27 UTC, kswenson approved these changes
👍 I think it would still be good to improve the comment for the `-webkit`-only CSS rules, but I'll approve and leave that to your discretion.

2023-01-10 05:27 UTC, kswenson commented on v3/src/components/graph/components/inspector-panel/point-format-panel.scss
> +    background-color: gray;
I don't think my questions are answered by the new comment.

2023-01-11 18:03 UTC, merged