Add Graph Tile automation tests
concord-consortium/codap pull request #642
Opened 2023-01-24 15:17 UTC by tejal-shah

@kswenson , @eireland ,
Below are the changes in this PR:
- Added tests for Graph tile (various plot transitions, but not checking against image snapshots yet), tests for Axes and Legend
- Added cypress support for being able to run tests in staging (https://codap3.concord.org/index-staging.html) in addition to dev (https://codap3.concord.org/branch/main/) and local
- Added MouseSensor to `v3/src/components/codap-dnd-context.tsx` - without this I couldn't get drag and drop to work as cited here - https://github.com/clauderic/dnd-kit/issues/208 . But unfortunately, this is breaking some functionality in the case table like renaming attributes, opening edit attribute properties modal because of which I had to skip a few table tests. And breaking this functionality is not desirable at all, we should not merge this PR until we fix this. But I'll need dev help in making this MouseSensor to work without breaking these features and get drag and drop to work.

2023-01-25 02:55 UTC, kswenson requested changes
👍 It's great that we're this close to having cypress tests that work for the graph and in particular for drag/drop. We obviously need to solve the issues you raise, but it seems like you're on the right track. I made some suggestions in inline comments but if necessary we can get together as well.

2023-01-26 06:23 UTC, kswenson commented on v3/cypress/support/commands.ts
> +    })
I did a simple test and the "pointerMoveBy" command didn't work as well as the "mouseMoveBy" command. 😞 So I went ahead and implemented the url parameter for enabling the mouse sensor only for tests that require it.

2023-01-26 06:24 UTC, kswenson commented on v3/src/components/codap-dnd-context.tsx
> +                    useSensor(MouseSensor))
I went ahead and added the url parameter for enabling the `MouseSensor` on demand for cypress tests.

2023-01-26 06:24 UTC, kswenson commented on v3/cypress/e2e/attribute_types_test.spec.ts
> +        const url = `${Cypress.config("index")}`;
done

2023-01-26 06:27 UTC, kswenson requested changes
I went ahead and added the `mouseSensor` url parameter for enabling the `MouseSensor` on demand. There's a couple of things worth addressing before merging the PR:
- we've standardized on hyphens rather than underscores for filenames, so cypress test filenames should follow that convention
- some of the legend tests were failing when I did a quick test

2023-01-26 15:40 UTC, tejal-shah commented on v3/cypress/support/commands.ts
> +    })
Yeah, that was the first thing I had tried before even adding the mousedown, mouseup and mousemove here.

2023-01-26 15:40 UTC, tejal-shah commented on v3/src/components/codap-dnd-context.tsx
> +                    useSensor(MouseSensor))
Yay, thank you!

2023-01-26 15:45 UTC, tejal-shah commented on v3/package.json
> +    "test:cypress:staging": "cypress run --env testEnv=staging",
Sending the testEnv as an environment param makes the cypress tests use the corresponding `config/cypress.<testEnv>.json` which have the environment specific baseUrls configured:
For example, staging's baseUrl is set to `https://codap3.concord.org/index-staging.html` and for dev it is `https://codap3.concord.org/branch/main/`

2023-01-26 17:30 UTC, tejal-shah commented
- I've now renamed files, for some to use hyphens and for others made the anme shorter so we don't need underscores or hyphens
- The legend tests were failing because they were visiting the base urls again and hence needed setting the mouseSensor param in their queryParams too - I've fixed this and they should now all pass.

2023-01-26 19:40 UTC, kswenson approved these changes
👍 LGTM

2023-01-27 04:57 UTC, merged