Drag drop move component
concord-consortium/codap pull request #671
Opened 2023-03-01 07:58 UTC by eireland

Drag and drop component tiles in free tile layout.
Click on title text brings up edit title mode. Need to fix mousedown and drag allows for both edit and drag of tile.

2023-03-02 02:14 UTC, kswenson requested changes
👍 Generally looks good -- the usual handful of suggestions on various topics. There's obviously some z-index issues to work out with some of the elements but those can wait for a subsequent PR.

2023-03-02 02:16 UTC, kswenson commented
Also, it seems like there must be a simplification of the title bar code lurking somewhere nearby, but I can't quite wrap my head around it and in any case it can wait for a subsequent PR.

2023-03-02 16:51 UTC, bfinzer approved these changes
👍🏻Deferring to Kirk

2023-03-06 18:43 UTC, kswenson approved these changes
👍 Changes look good

2023-03-07 01:12 UTC, kswenson approved these changes
👍 Looks good -- just one stale comment to remove

2023-03-07 01:12 UTC, kswenson commented on v3/src/components/dnd-detect-collision.ts
> +    // apply the collection detection function specified by the tile
```suggestion
```
This comment is not relevant in this context.

2023-03-07 19:07 UTC, merged