Adds default heights to slider and calculator
concord-consortium/codap pull request #725
Opened 2023-03-28 23:38 UTC by eireland

Fixes height and width for newly opened sliders and calculators to a default value

2023-03-28 23:41 UTC, kswenson requested changes
I removed these defaults intentionally. For fixed-size components, the sizes should be defined by the component, not by the registration. If there's something you're trying to achieve here we should talk about it.

2023-03-29 18:43 UTC, bfinzer approved these changes
I defer to Kirk wrt default sizes

2023-04-04 01:25 UTC, kswenson approved these changes
👍 @eireland and I looked at this together and determined that it is appropriate for the `defaultWidth` and `defaultHeight` to be specified in registration for fixed-size components because the auto-placement code requires it. Instead, the `FreeTileComponent` no longer imposes a dynamic width/height on fixed-size components.

2023-04-04 01:25 UTC, kswenson commented on v3/src/components/slider/slider-registration.ts
> +    defaultHeight: 73
```suggestion
  defaultHeight: 73
```

2023-04-04 15:01 UTC, merged