case table CollectionTitle improvements
concord-consortium/codap pull request #739
Opened 2023-04-04 19:33 UTC by hmorgancode

2023-04-04 21:28 UTC, hmorgancode commented
ah, codecov has informed me that I did not add coverage for this

2023-04-05 00:01 UTC, kswenson requested changes
👍 This is heading in the right direction. I had two broad suggested improvements, one of which I ended up implementing myself because I wanted to test it out before suggesting it:
1. Re-simplify the props of the `CollectionTitle` component for reasons given in inline comments. (This one I left for you.)
2. Simplify the `CollectionTitle` implementation so it's not relying on render counts. (This one I ended up implementing in an additional commit. See what you think and we can discuss tomorrow if you'd like.)

2023-04-05 18:58 UTC, hmorgancode commented on v3/src/components/case-table/collection-title.tsx
> +    }
Good call! I was unaware of ResizeObservers

2023-04-05 20:18 UTC, kswenson approved these changes
👍 Looks good -- just one remaining issue of a hard-coded string

2023-04-05 20:18 UTC, kswenson commented on v3/src/components/case-table/collection-title.tsx
> +        <Editable value={isEditing ? title : `${title} (${caseCount} cases)`}
Replace `cases` with an appropriate translated string. Something like the following from `SummaryView`:
```typescript
  const casesStr = t(caseCount === 1 ? "DG.DataContext.singleCaseName" : "DG.DataContext.pluralCaseName")
```

2023-04-06 17:40 UTC, merged