fix: Removing axis attributes does not remove line (PT-185639677)
concord-consortium/codap pull request #843
Opened 2023-07-19 03:01 UTC by emcelroy

PT Story: https://www.pivotaltracker.com/story/show/185639677

Changes the `Adornments` component so it will skip adding adornments in the Graph model that don't support the current plot type. This also fixes a separate bug identified in this [PT story](https://www.pivotaltracker.com/story/show/185639448). In addition, there is some clean up of the Movable Point component that removes unnecessary code and fixes an issue where the point moved incorrectly when axis attributes were removed or changed.

2023-07-19 03:04 UTC, emcelroy commented on v3/src/components/graph/adornments/movable-point/movable-point.tsx
> -    if (!model.points) return
These `if (!model.points) return` lines were introduced while troubleshooting a problem I ran into in the Add Movable Point PR. They aren't necessary. I should have removed them after solving the problem, but forgot.

2023-07-20 03:48 UTC, kswenson requested changes
👍 Generally looks good -- I added a commit which:
- moves the initial creation of the points from the React component to the model
- uses the `DataConfigurationModel` for determining categories rather than the `GraphLayout`
- fixes the D3 types

Serialization in the split case doesn't work perfectly, but I can't tell whether that's related to what I did or a preexisting issue. It may be related to the fact that split axes don't restore properly even without adornments, which seems to be a preexisting condition. In any case, I'm turning it over to you to take it from here.

2023-07-21 19:50 UTC, emcelroy commented
As discussed elsewhere, there is a remaining issue where the movable point will not be correctly placed when an attribute is removed from an axis, and then a new attribute is added to that axis. There are changes required outside the realm of adornments, however, to fix that problem. This code should work correctly for placing the movable point correctly in that case once those changes are made.

2023-07-21 20:38 UTC, kswenson approved these changes
👍 Looks good!

2023-07-21 21:09 UTC, merged