Do not serialize values computed by formulas, make formula attrs non-editable
concord-consortium/codap pull request #982
Opened 2023-11-07 12:09 UTC by pjanik

https://www.pivotaltracker.com/story/show/186424226

This PR ensures that values computed by formulas will not be serialized in both development and production modes. I've also modified the top-level attribute file comment because, unfortunately, prepareSnapshot() and completeSnapshot() are no longer no-ops in production.

Additionally, I've added a semi-related feature (mostly due to it being overdue for a long time) - formula cells are now non-editable.

2023-11-07 23:30 UTC, kswenson requested changes
👍 Looks good -- I hadn't thought about the implications of formulas for `preapreSnapshot`/`completeSnapshot`, but I'm glad that supporting them wasn't too difficult. The one requested change is to the handling of editability -- see comment elsewhere.

2023-11-07 23:30 UTC, kswenson commented on v3/src/models/data/attribute.ts
> +    this.setEditable(displayFormula === "")
The `editable` property is meant to correspond to the user's ability to specify editability. I think for this purpose a better solution would be to add a view like:
```
  get isEditable() {
    return self.editable && !self.displayFormula
  }
```

2023-11-08 15:46 UTC, pjanik commented
Thank you, @kswenson. It definitely makes sense. I've just pushed a commit that adds this new view. I'm requesting a re-review just to ask if you can think of any other part of the app, apart from the user cells, that should now use "isEditable" instead of "editable"?

2023-11-08 17:24 UTC, kswenson approved these changes
>I'm requesting a re-review just to ask if you can think of any other part of the app, apart from the use-cells, that should now use "isEditable" instead of "editable"?

That's the only one that comes to mind.

2023-11-08 19:18 UTC, merged